# Generated by Django 4.0.4 on 2022-09-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_multiproductimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='(products/<django.db.models.fields.CharField>)'),
        ),
    ]
