# Generated by Django 4.0.4 on 2022-09-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_image2_product_image3_product_image4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.AlterField(
            model_name='multiproductimage',
            name='images',
            field=models.ImageField(upload_to='products/%Y/%m/%d'),
        ),
    ]
