# Generated by Django 4.0.4 on 2022-09-30 15:40

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_post_multiproductimage_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiproductimage',
            name='images',
            field=models.ImageField(upload_to='products/%Y/%m/%d', verbose_name=shop.models.Product),
        ),
    ]
