# Generated by Django 4.0.4 on 2022-10-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_multiproductimage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='multiproductimage',
            name='images',
            field=models.ImageField(upload_to='products/%Y/%m/%d'),
        ),
    ]
