# Generated by Django 4.0.4 on 2022-10-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_main_image_alter_multiproductimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
