# Generated by Django 4.0.4 on 2022-10-19 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_stockproduct_remove_product_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproduct',
            name='stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
