# Generated by Django 4.0.4 on 2022-10-19 23:09

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_stockproduct_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproduct',
            name='stock_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='stock',
            field=models.IntegerField(default=0, verbose_name=shop.models.Product),
        ),
    ]
