# Generated by Django 4.0.4 on 2022-10-19 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_stockproduct_stock_id_alter_stockproduct_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockProduct',
        ),
    ]
