# Generated by Django 4.0.4 on 2022-10-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_stockproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockProduct',
        ),
    ]
