# Generated by Django 4.1.2 on 2022-11-04 13:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expedition',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material_used',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
