# Generated by Django 4.1.2 on 2022-11-28 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_product_expedition_product_material_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_category', to='shop.category')),
                ('image_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_category', to='shop.category')),
            ],
        ),
    ]
