# Generated by Django 4.1.2 on 2022-11-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_featuredcollections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredcollections',
            name='image_category',
        ),
    ]
