# Generated by Django 4.1.2 on 2022-11-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_remove_featuredcollections_image_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_featured_home_page',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FeaturedCollections',
        ),
    ]
