# Generated by Django 4.0.4 on 2022-10-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='total_price_per_product',
            field=models.IntegerField(default=0),
        ),
    ]
